### ISSUE TITLE
Current version doesn't work with 3.10

### ISSUE THREAD

**Issue by rrthomas** [negesti/gnome-shell-extensions-negesti#77]
The problem is that nothing happens when I press configured key shortcuts. From the behaviour of the caret in a terminal window, it is being trapped (because the window briefly loses focus, whereas when I press an unbound key, nothing happens), but the window does not move.

I can't see any more how to test numbered releases from extensions.gnome.org, so instead I checked out the git repo and tried a version that seemed likely to work (since I'm a bit short of time right now). I tried commit 30b3deb, just before the 3.14 update, and it worked fine.

If it's useful I can bisect where it starts failing later.

**Comment by negesti** [comment]
hm, maybe you can get some useful info if you start the shell from a terminal
e.g. 
     gnome-shell --replace &

I guess it's an api change that causes a syntax error...

**Comment by rrthomas** [comment]
When I try to move a window, I get:

    (gnome-shell:1651): Gjs-WARNING **: JS ERROR: TypeError: win.get_frame_rect is not a function
    MoveWindow.prototype._getCurrentScreenIndex@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:140
    MoveWindow.prototype._moveToScreen@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:177
    MoveWindow.prototype.moveToScreen@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:161
    MoveWindow.prototype._init/<@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:887

**Comment by negesti** [comment]
Can you please test the current develop branch? Should work now

**Comment by rrthomas** [comment]
I get the same error (the last line number is different, though, I guess because of code changes):

    (gnome-shell:8448): Gjs-WARNING **: JS ERROR: TypeError: win.get_frame_rect is not a function
    MoveWindow.prototype._getCurrentScreenIndex@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:140
    MoveWindow.prototype._moveToScreen@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:177
    MoveWindow.prototype.moveToScreen@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:161
    MoveWindow.prototype._init/<@/home/rrt/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/extension.js:891

**Comment by negesti** [comment]
right, monkey patch should be applied in the correct order...
hope it works now

**Comment by rrthomas** [comment]
I get exactly the same errors as the last time. I've double-checked that my repo is up to date (and indeed I saw the reversing patch). Thanks for persevering with this!

**Comment by negesti** [comment]
Can you start LookingGlas (Alt + F2 "lg") an post the output of the following commands: 
    
      imports.misc.config.PACKAGE_VERSION

      Meta.Window.prototype.get_outer_rect

      Meta.Window.prototype (this will open a new window when clicked)

**Comment by rrthomas** [comment]
Respectively:

    3.10.4
    <js_function>

For the last one, Meta.Window.prototype, I can't copy the text in the window that opens, and obviously it's a list of the properties of the object; what exactly did you want to know?

**Comment by negesti** [comment]
ok i thought you have 3.14 installed. commit is on the way

**Comment by rrthomas** [comment]
Sorry, I thought the issue title made my version obvious, but now I see my original comment was a bit ambiguous!

**Comment by negesti** [comment]
true, i should really uninstall maxmus again :)

**Comment by rrthomas** [comment]
I spoke too soon. When I move a window to the left/right screen, sometimes as soon as I let go of the keys, the window springs back to the screen it was on before.

**Comment by negesti** [comment]
no problem, always glad to hear, that people are actually using the extension
