### ISSUE TITLE
moving focus stopped working with gnome shell version 3.34

### ISSUE THREAD

**Issue by tocomo** [negesti/gnome-shell-extensions-negesti#171]
gnome-shell  Version: 3.34.1-1ubuntu1 throws errors:

Nov 18 11:37:59 ... gnome-shell[9258]: JS ERROR: TypeError: this._construct is not a function
                                              newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                              _flashWindow@/home/tobias/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:156:21
                                              _activateWindow@/home/tobias/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:166:7
                                              _focusNearestCandidate@/home/tobias/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:498:5
                                              _moveFocus@/home/tobias/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:473:5
                                              _enable/<@/home/tobias/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:176:36

**Comment by negesti** [comment]
I'm not using 3.34 yet, maybe @73 can check this?

**Comment by 73** [comment]
Will do on Monday.

**Comment by 73** [comment]
Okay, the code related to flashing the window on focus change is broken. I vote for removing the code. Moving focus works, but animation does not.

**Comment by negesti** [comment]
Sounds fine for me
